import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

import { FieldServiceReportData } from "../types/report";

export function exportFieldServiceReport(
  report: FieldServiceReportData
): void {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();

  // ===== Title =====

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);

  doc.text(
    "FIELD SERVICE REPORT",
    pageWidth / 2,
    20,
    {
      align: "center",
    }
  );

  // ===== Information =====

  autoTable(doc, {
    startY: 30,
    theme: "grid",
    head: [["Field", "Value"]],
    body: [
      ["Publisher", report.publisherName],
      ["Month", `${report.month} ${report.year}`],
      ["Participation", report.participation],
      ["Hours", report.hours.toFixed(2)],
      ["Bible Studies", report.bibleStudies.toString()],
    ],
    styles: {
      fontSize: 11,
    },
    headStyles: {
      fillColor: [41, 98, 255],
    },
  });

  // ===== Comments =====

  const commentsY =
    (doc as any).lastAutoTable.finalY + 15;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);

  doc.text("Comments", 14, commentsY);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  const comments =
    report.comments.trim() ||
    "No comments provided.";

  const wrapped = doc.splitTextToSize(
    comments,
    180
  );

  doc.text(wrapped, 14, commentsY + 8);

  // ===== Footer =====

  const footerY = 285;

  doc.setDrawColor(180);
  doc.line(
    14,
    footerY - 5,
    pageWidth - 14,
    footerY - 5
  );

  doc.setFontSize(9);

  doc.text(
    `Generated on ${new Date().toLocaleDateString()}`,
    14,
    footerY
  );

  doc.text(
    "Generated by JW Meeting Companion",
    pageWidth - 14,
    footerY,
    {
      align: "right",
    }
  );

  // ===== Save =====

  const filename = `${report.publisherName.replace(
    /\s+/g,
    "_"
  )}_${report.month}_${report.year}_Field_Service_Report.pdf`;

  doc.save(filename);
}