import {
  Content,
  TableCell,
} from "pdfmake/interfaces";

import { PdfColors } from "./PdfColors";

export interface PdfCoverOptions {
  title: string;
  subtitle?: string;
  description?: string;
}

export function createPdfCover(
  options: PdfCoverOptions
): Content {
  const {
    title,
    description,
  } = options;

  const stack: any[] = [
    {
      text: title,
      style: "coverTitle",
      margin: [0, 10, 0, 14],
    },
  ];

  stack.push({
    canvas: [
      {
        type: "line",
        x1: 120,
        y1: 0,
        x2: 380,
        y2: 0,
        lineWidth: 0.8,
        lineColor: "#FFFFFF",
      },
    ],
    margin: [0, 0, 0, 24],
  });

  if (description) {
    stack.push({
      text: description,
      color: "#FFFFFF",
      alignment: "center",
      italics: true,
      fontSize: 12,
      margin: [0, 0, 0, 36],
    });
  }

  stack.push({
    text: "Generated by JW Meeting Companion",
    alignment: "center",
    color: "#DCE8F7",
    fontSize: 10,
  });

  return {
    table: {
      widths: ["*"],

      body: [
        [
          {
            stack,

            fillColor:
              PdfColors.primary,

            margin: [30, 60, 30, 60],

            border: [
              false,
              false,
              false,
              false,
            ],
          } as TableCell,
        ],
      ],
    },

    layout: "noBorders",

    margin: [0, 0, 0, 36],
  };
}