import {
  PDFDocument,
  StandardFonts,
  rgb,
} from "pdf-lib";

import { ExportDocument } from "./exportTypes";

export async function exportToPdf(
  exportDoc: ExportDocument
): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();

  let page = pdf.addPage();

  const titleFont = await pdf.embedFont(
    StandardFonts.HelveticaBold
  );

  const bodyFont = await pdf.embedFont(
    StandardFonts.Helvetica
  );

  const margin = 50;

  const pageHeight = page.getHeight();
  const pageWidth = page.getWidth();

  let y = pageHeight - margin;

  function ensureSpace(required = 80) {
    if (y < required) {
      page = pdf.addPage();
      y = page.getHeight() - margin;
    }
  }

  page.drawText("JW Meeting Companion", {
    x: margin,
    y,
    size: 22,
    font: titleFont,
    color: rgb(0.12, 0.32, 0.72),
  });

  y -= 40;

  page.drawText(exportDoc.title, {
    x: margin,
    y,
    size: 18,
    font: titleFont,
  });

  y -= 22;

  if (exportDoc.subtitle) {
    page.drawText(exportDoc.subtitle, {
      x: margin,
      y,
      size: 12,
      font: bodyFont,
    });

    y -= 20;
  }

  page.drawText(
    `Created: ${exportDoc.createdAt}`,
    {
      x: margin,
      y,
      size: 10,
      font: bodyFont,
    }
  );

  y -= 16;

  page.drawText(
    `Updated: ${exportDoc.updatedAt}`,
    {
      x: margin,
      y,
      size: 10,
      font: bodyFont,
    }
  );

  y -= 30;

  for (const section of exportDoc.sections) {
    ensureSpace();

    page.drawText(section.title, {
      x: margin,
      y,
      size: 14,
      font: titleFont,
    });

    y -= 18;

    page.drawText(
      section.content || "-",
      {
        x: margin,
        y,
        size: 11,
        font: bodyFont,
        maxWidth: pageWidth - margin * 2,
        lineHeight: 14,
      }
    );

    const lines = Math.max(
      1,
      Math.ceil(
        (section.content || "-").length / 80
      )
    );

    y -= lines * 14 + 28;
  }

  page.drawText(
    "Generated by JW Meeting Companion",
    {
      x: margin,
      y: 30,
      size: 9,
      font: bodyFont,
      color: rgb(0.4, 0.4, 0.4),
    }
  );

  return pdf.save();
}