import type {
  Content,
  TDocumentDefinitions,
} from "pdfmake/interfaces";

import type { Meeting } from "../models/Meeting";

import {
  pdfPageMargins,
  pdfStyles,
} from "./pdfTheme";

export function createMeetingPdfDocument(
  meeting: Meeting
): TDocumentDefinitions {
  const congregationName =
    meeting.info.congregation ||
    "My Congregation";

  const attendance: Content[] =
    meeting.attendance.length > 0
      ? meeting.attendance.map(
          (member) => ({
            text: `${member.present ? "✓" : "☐"} ${member.name}`,
            margin: [0, 2, 0, 2],
          })
        )
      : [
          {
            text: "No attendance recorded.",
          },
        ];

  const agenda: Content[] =
    meeting.agenda.length > 0
      ? meeting.agenda.flatMap(
          (item, index) => [
            {
              text: `${index + 1}. ${item.title}`,
              style: "sectionHeader",
            },

            {
              columns: [
                {
                  text: [
                    {
                      text: "Proposed By: ",
                      style: "label",
                    },
                    item.proposedBy || "-",
                  ],
                },

                {
                  text: [
                    {
                      text: "Duration: ",
                      style: "label",
                    },
                    `${item.duration} min`,
                  ],
                  alignment: "right",
                },
              ],
              margin: [0, 0, 0, 6],
            },

            {
              text: [
                {
                  text: "Reference: ",
                  style: "label",
                },
                item.reference || "-",
              ],
              margin: [0, 0, 0, 4],
            },

            {
              text: [
                {
                  text: "Notes: ",
                  style: "label",
                },
                item.notes || "No notes.",
              ],
              margin: [0, 0, 0, 12],
            },
          ]
        )
      : [
          {
            text: "No agenda items.",
          },
        ];

  return {
    pageMargins: pdfPageMargins,

    styles: pdfStyles,

    footer: (
      currentPage,
      pageCount
    ) => ({
      text: `JW Meeting Companion • Page ${currentPage} of ${pageCount}`,
      style: "footer",
    }),

    content: [
      {
        text: congregationName,
        style: "title",
      },

      {
        text: "Body of Elders Meeting",
        style: "subtitle",
      },

      {
        text:
          "Generated by JW Meeting Companion",
        style: "subtitle",
      },

      {
        text: "Meeting Information",
        style: "sectionHeader",
      },

      {
        columns: [
          [
            {
              text: [
                {
                  text: "Congregation: ",
                  style: "label",
                },
                meeting.info.congregation ||
                  congregationName,
              ],
            },

            {
              text: [
                {
                  text: "Date: ",
                  style: "label",
                },
                meeting.info.meetingDate ||
                  "-",
              ],
            },

            {
              text: [
                {
                  text: "Time: ",
                  style: "label",
                },
                meeting.info.meetingTime ||
                  "-",
              ],
            },
          ],

          [
            {
              text: [
                {
                  text: "Chairman: ",
                  style: "label",
                },
                meeting.info.chairman ||
                  "-",
              ],
            },

            {
              text: [
                {
                  text: "Opening Prayer: ",
                  style: "label",
                },
                meeting.info.openingPrayer ||
                  "-",
              ],
            },

            {
              text: [
                {
                  text: "Closing Prayer: ",
                  style: "label",
                },
                meeting.info.closingPrayer ||
                  "-",
              ],
            },
          ],
        ],
      },

      {
        text: "Attendance",
        style: "sectionHeader",
      },

      ...attendance,

      {
        text: "Agenda",
        style: "sectionHeader",
      },

      ...agenda,

      {
        text: "General Minutes",
        style: "sectionHeader",
      },

      {
        text:
          meeting.minutes ||
          "No meeting minutes recorded.",
      },
    ],
  };
}